# Monitoring options
monitor: true               # generate monitoring files
node_status: false          # print node status when running jobs
job_status: false            # print job status when running or stopping jobs
raw_id: false                # use raw job IDs in job configurations

# disaggregation option
disaggregation: true

# Cluster configurations
racks: 6                    # total number of racks
compute_nodes: 220          # number of compute nodes in each rack
memory_nodes: 20             # number of memory nodes in each rack
compute_node_capacity: 256  # memory capacity of the compute node (in GB)
memory_node_capacity: 2048     # memory capacity of the memory node (in GB)
memory_granularity: 2       # memory allocation granularity (in GB)

# Jobs configuration
offset: 0                   # offset in the job configuration file
number: 100                  # number of jobs to be loaded. Load all jobs if set to zero

# Scheduler algorithms  
algorithm: "fcfs"           # Supported algorithms: fcfs, random, rack_aware
